Practice task. Console calculator
avsokolovskiy/console-calculator pull request #1
Opened 2022-10-03 10:47 UTC by avsokolovskiy

Task : https://brainly.atlassian.net/wiki/spaces/QA/pages/1052312433/2.+Python#2.2.2.-Practice.-Console-calculator
Screenshot:
![image](https://user-images.githubusercontent.com/105415686/193558881-29f68094-6d3e-4eb1-bff3-7698254c58f7.png)
Implemented: 
UX
[+] Application should greet the user after the first run
[+] Application should provide an instruction to the user after the first run
[+] Application should provide correct validation message for the user if he did something wrong
[+] Application should say goodbye when user wants to quit
Input
[+] Application should take two digits as input from the terminal
[+] Application should take one of the following actions as an input from the terminal (+, -, *, /)
Output
[+] Application should output the result of an action
[+] Result of all actions should be rounded to 3 decimals
Validation
[+] Correct validation for all incorrect inputs should be implemented
Exit
[+] User should be able to exit from an application on any stage
Documentation
[+] README.md file with instruction of how download application from GitHub, install it and run it from the terminal should be added

2022-10-05 08:37 UTC, marcinoleksiak requested changes
pretty cool :)
try to address my comments + check your code with pylint + use code formatted.

let's not introduce any more changes for now. we will see what results we will have after unit tests! :)

2022-10-05 08:37 UTC, marcinoleksiak commented on main.py
> +    while flag:
```flag=True```
is problematic. after installation of `pylint` you will get an error about shadowing a name from the outer scope. think about solving this.
you can use `while True` and not the `flag`. this is one of the possibilities.

2022-10-05 08:37 UTC, marcinoleksiak commented on main.py
> +            print('{} {} {} = {}'.format(operand_1, operator, operand_2, result))
Let's try to modify this to display:
3 + 3 = 6
instead of
3 + 3 = 6.0

2022-10-05 08:37 UTC, marcinoleksiak commented on main.py
> +    operand_2 = round(float(operand_2), 3)
let's do the rounding after the calculation result, not before - this can cause calculation errors

2022-10-05 08:37 UTC, marcinoleksiak commented on main.py
> +        return operand_1 / operand_2
there's a very smart function built-in in python: `eval`. it takes a string and can execute math operations
example: 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/33527461/194016575-084e7b21-adc8-4b36-a0ab-b6f3dd73b31a.png">

2022-10-05 08:37 UTC, marcinoleksiak commented on main.py
> +        return operand_1 / operand_2
it can also handle cases like this:
<img width="158" alt="image" src="https://user-images.githubusercontent.com/33527461/194016751-843f9a14-1a81-466a-8902-7f8c972751c6.png">

basically `-1` and `(-1)` are the same

2022-10-05 08:37 UTC, marcinoleksiak commented on main.py
> +            float(operand)
you check here if `number` can be converted to `float` if yes then you return a string. but you can return this float value and later you can avoid duplications -> in lines 41 and 42 you cast that string again -> small optimisation.

2022-10-09 17:35 UTC, avsokolovskiy commented on main.py
> +    while flag:
Fixed

2022-10-09 17:54 UTC, avsokolovskiy commented on main.py
> +            float(operand)
implemented

2022-10-09 17:55 UTC, avsokolovskiy commented on main.py
> +    operand_2 = round(float(operand_2), 3)
Fixed

2022-10-09 17:55 UTC, avsokolovskiy commented on main.py
> +            print('{} {} {} = {}'.format(operand_1, operator, operand_2, result))
Fixed

2022-10-09 18:00 UTC, avsokolovskiy commented on main.py
> +        return operand_1 / operand_2
Noted, but in my case, I'm converting operands in the get_operand function, and passing a number, not a string, do you think I need to rewrite my code and use this function instead of my approach?

2022-10-10 12:42 UTC, marcinoleksiak requested changes

2022-10-10 12:42 UTC, marcinoleksiak commented on Pipfile
that's great you've added a Pipfile that defines the virtual environment.
small comment here - you added `pylint` in the `packages` section. however, we put here only packages that are required for the final app to work outside your development environment. `pylint` is a tool for static analysis of your code. it can tell you what weaknesses are in your code. it should be placed in `dev-packages` section

2022-10-10 12:42 UTC, marcinoleksiak commented on Pipfile
to install dev package you need to run command: `pipenv install --dev`

example outcome:
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/33527461/194867288-103eae0d-6465-4eca-806d-1ab4788dd6ae.png">

2022-10-12 19:31 UTC, avsokolovskiy commented on Pipfile
fixed

2022-10-14 06:57 UTC, marcinoleksiak approved these changes

2022-10-29 18:28 UTC, merged