Practice task unit tests.
avsokolovskiy/console-calculator pull request #3
Opened 2022-10-29 18:44 UTC by avsokolovskiy

Task: https://brainly.atlassian.net/wiki/spaces/QA/pages/1052312433/2.+Python#2.2.4.-Practice.-Unit-tests
Implemented:
[+] Use your check-list from p.2.2.3 to cover your calculator by unit tests.
[+] Update your README.md file with instructions on how to run unit tests from the terminal.
[+] Use the following tech stack for this task: python 3, unittest.
[+] Use a separate git branch for this task.
[+] Open pull request.

2022-11-02 14:57 UTC, marcinoleksiak requested changes
hey :)
basically really nice job. I like the way. you handled tests parameterization!

2022-11-02 14:57 UTC, marcinoleksiak commented on test_calc.py
> +        self.assertEqual(VALID_OPRND_ARG, str(test_oprnd))
here I'd change the casting to this way:
`self.assertEqual(int(VALID_OPRND_ARG), test_oprnd)`
cometic change but: you mock user input with string 32, and you expect that your function will return you an int value. so it's better to expect and int here instead of casting it to string. If your method returned str instead of int, your test would pass

2022-11-02 14:57 UTC, marcinoleksiak commented on test_calc.py
> +        # pass
note that in your calc you catch the ValueError and you handle it:
```python        
    except ValueError:
        print('Not a number. Please enter a valid number')
```
so you need to check the console output here :)

2022-11-02 14:57 UTC, marcinoleksiak commented on test_calc.py
> +        # pass
additional thing is an infinite loop. you need to run it twice. first time to get error handling (console output) and the second run that will cause break in the loop (try to use `side_effect`)

2022-11-02 14:57 UTC, marcinoleksiak commented on test_calc.py
> +        # pass
remark with breaking the loop the same as in previous comment

2022-11-02 14:57 UTC, marcinoleksiak commented on test_calc.py
> +        self.assertRaises(Exception, calc_main.calculation, '5', '0', '/')
this test does not actually check what your calc does. you check for 0-division in `__main__` part that does not belong to any function.
you have:
```python
if __name__ == '__main__':
    print_greetings()
    print_instruction()
    while True:
        print('----------------------------------------------------------')
        oprnd_1 = get_operand(number='1')
        oprnd_2 = get_operand(number='2')
        oprtr = get_operator()
        if oprnd_2 == '0' and oprtr == '/':
            print('Division by zero is prohibited.')
        else:
            result = round(calculation(operand_a=oprnd_1, operand_b=oprnd_2, akt_operator=oprtr), 3)
            print(f'{oprnd_1} {oprtr} {oprnd_2} = {result}')
```

honestly I don't know the way how to test the content of "__main__" condition. Since unit testing is not the most important in this course let's move a whole infinite loop to another function `run_calc()` and create some separated tests for it :)

2022-11-10 08:20 UTC, avsokolovskiy commented on test_calc.py
> +        self.assertEqual(None, context_manager.exception.code)
fixed

2022-11-10 08:20 UTC, avsokolovskiy commented on test_calc.py
> +        self.assertEqual(None, context_manager.exception.code)
fixed

2022-11-10 08:20 UTC, avsokolovskiy commented on test_calc.py
> +        test_obj = str(captured_output.getvalue()).strip()
fixed

2022-11-10 08:22 UTC, avsokolovskiy commented on test_calc.py
> +        self.assertEqual(VALID_OPRND_ARG, str(test_oprnd))
fixed

2022-11-10 08:22 UTC, avsokolovskiy commented on test_calc.py
> +        # pass
fixed

2022-11-10 08:23 UTC, avsokolovskiy commented on test_calc.py
> +        # pass
fixed

2022-11-12 18:57 UTC, avsokolovskiy commented on test_calc.py
> +test_data_dev = [[4, 2, 2], [5, 2, 2.5], [-10, -2, 5], [8, -2, -4], [0, 5, 0], [8, 3.2, 2.5]]
fixed

2022-11-12 18:57 UTC, avsokolovskiy commented on test_calc.py
> +        self.assertRaises(Exception, calc_main.calculation, '5', '0', '/')
fixed

2022-11-14 16:11 UTC, marcinoleksiak approved these changes

2022-11-14 16:11 UTC, marcinoleksiak commented
Well done :)
Lets move to the next part

2022-11-14 17:55 UTC, merged